// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

#include <iostream>
using namespace std;

int sum_even_fib(int n)
{
    int a = 0, b = 1, c, sum = 0;

    while (true)
    {
        c = a + b;
        a = b;
        if (c >= n)
            break;
        b = c;

        if(b % 2 == 0)
            sum += b;
    }
    return sum;
}

int main()
{
    int n = 4000000;

    cout << sum_even_fib(n) << endl;

    return 0;
}